# -*- coding: utf-8 -*-
"""Python Assignments.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/114BsKZt4Yhyuu2V8HX8Dt9oaNu9Dk177
"""

print("Hello world")